imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: tr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: test@test.com
        sender_name: Test

easy_admin:
    site_name: 'Admin Paneli'
    entities:
        Category:
            class: AppBundle\Entity\Category
            label: "Kategoriler"
            list:
                title: "Kategoriler"
                fields:

                    - { property: 'title', label: 'Kategori Başlığı' }
                    - {property: 'makaleler'}
            form:
                title: "Kategori Ekle"
                fields:
                    - { property: 'title', label: 'Kategori Başlığı' }

        Article:
            class: AppBundle\Entity\Article
            label: "Yazılar"
            list:
                title: "Yazılar"
                fields:
                - { property: 'title', label: 'Başlık' }
                - { property: 'category', label: 'Kategori' }

            form:
                title: "Yazı Ekle"
                fields:
                    - { property: 'title', label: 'Başlık' }
                    - { property: 'content', label: 'İçerik' }
                    - { property: 'category', label: 'Kategori' }

        User:
            class: AppBundle\Entity\User
            label: "Kullanıcılar"
            list:
                title: "Kullanıcılar"
                fields:
                    - { property: 'username',label: 'Kullanıcı adı' }
                    - { property: 'email', type: 'email', label: 'E-mail adresi' }
                    - { property: 'enabled', label: 'Aktif mi?', type: 'toggle'}
            form:
                title: "Kullanıcı Ekle"
                fields:
                    - { property: 'username',label: 'Kullanıcı adı' }
                    - { property: 'email', type: 'email', label: 'E-mail adresi' }
                    - { property: 'plainPassword', type: 'password',label: 'Parola' }
                    - { property: 'enabled', label: 'Aktif mi?'}

stof_doctrine_extensions:
    orm:
        default:
            sluggable:   true
            timestampable: true